### ISSUE TITLE
New name for getting started guide

### ISSUE THREAD

**Issue by kersten1** [riscv-admin/riscv-getting-started-guide#2]
Create a new name for getting started guide. New member guide?

**Comment by kersten1** [comment]
@jjscheel I like "New member guide".  How much input do we need for this decision?

**Comment by jjscheel** [comment]
42

**Comment by kersten1** [comment]
Technical member on-boarding guide it is then...

**Comment by jjscheel** [comment]
@rpsene likes names.  Perhaps his insight would be good?

**Comment by wmat** [comment]
I like "New Member Guide" personally.  Or even just "Member Guide" so as
not to dissuade old members from looking at it.

**Comment by kersten1** [comment]
RISC-V Technical Member Guide

**Comment by rpsene** [comment]
@kersten1 what kind of getting started are we promoting?

- [ ]  Getting started writing specs? 
- [ ] Getting started with tools?
- [ ] Getting started with Asciidoc?
- [ ] Other

**Comment by kersten1** [comment]
@rpsene This is the onboarding guide that we have for the technical members. Trying to come up with different name rather than using Getting started or onboarding. Because the guide is useful to existing members as well and should be used as a reference for all.

**Comment by jjscheel** [comment]
I generally like _New Member Guide_ name BUT would like to add something to describe that it's for engagement.   Perhaps we call it the _New Member Guide for Technical Collaboration_?

**Comment by kersten1** [comment]
That is a mouthful! I do like Bill's point about dropping the "new" though. It should be considered a reference for technical collaboration, IMHO. However, I will of course cave on this one. Also need to consider what the short name will be - Member Guide? Are there other member guides out there to be aware of?

**Comment by rpsene** [comment]
Looks like we have an opportunity to create something considering Ops, Tech and Markerting/Market.

**Comment by jjscheel** [comment]
There was another "Getting Started Guide" we've since renamed to something very specific...

**Comment by kersten1** [comment]
making a judge's ruling here and going with "Member's Guide for Technical Collaboration"
